#cloud-config
packages:
 - stress-ng
write_files:
-   content: |
      [Unit]
      Description = Simulate CPU Utilization
      [Service]
      ExecStart = /usr/bin/stress-ng -c 2 -l 60
      User = opc
      [Install]
      WantedBy = multi-user.target
    path: /etc/systemd/system/stress.service
runcmd:
 -  'echo $(date) | tee /home/opc/datemarker'
 -  ln -s /etc/systemd/system/stress.service /etc/systemd/system/multi-user.target.wants/stress.service
 -  systemctl enable stress.service
 -  systemctl start stress.service
